# Generated by Django 3.0.1 on 2020-01-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0009_auto_20200105_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', models.ImageField(blank=True, upload_to='processed_shots/NDVI')),
                ('ndre', models.ImageField(blank=True, upload_to='processed_shots/NDRE')),
                ('grvi', models.ImageField(blank=True, upload_to='processed_shots/GRVI')),
                ('gci', models.ImageField(blank=True, upload_to='processed_shots/GCI')),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('Picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Picture')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
            options={
                'verbose_name': 'Processed Data',
                'verbose_name_plural': 'Processed Data',
            },
        ),
    ]
