# Generated by Django 3.0.1 on 2020-01-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processeddata',
            old_name='Picture',
            new_name='picture',
        ),
    ]
