# Generated by Django 3.0.1 on 2019-12-31 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.CharField(max_length=120)),
                ('latitude', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Cordinate',
                'verbose_name_plural': 'Cordinates',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_lookup', models.CharField(auto_created=True, default='odzkxKUe', max_length=120)),
                ('farm_name', models.CharField(max_length=120)),
                ('farm_area', models.BigIntegerField()),
                ('farm_created_on', models.DateTimeField(auto_now_add=True)),
                ('coordinates', models.ManyToManyField(blank=True, null=True, to='farm.Coordinates')),
                ('farm_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_GRE', models.ImageField(blank=True, upload_to='arial_shots/GRE')),
                ('resource_NIR', models.ImageField(blank=True, upload_to='arial_shots/NIR')),
                ('resource_RED', models.ImageField(blank=True, upload_to='arial_shots/RED')),
                ('resource_REG', models.ImageField(blank=True, upload_to='arial_shots/REG')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('farm_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Farm')),
            ],
        ),
    ]
