# Generated by Django 3.0.1 on 2020-01-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_auto_20200101_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='ny0Eu937', max_length=120),
        ),
    ]
