# Generated by Django 3.0.1 on 2020-01-03 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_auto_20200101_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='C3pNxvS1', max_length=120),
        ),
    ]
