# Generated by Django 3.0.1 on 2020-01-05 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_auto_20200104_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='J14U3vBI', max_length=120),
        ),
        migrations.CreateModel(
            name='ProcessedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi', models.ImageField(blank=True, upload_to='processed_shots/NDVI')),
                ('ndre', models.ImageField(blank=True, upload_to='processed_shots/NDRE')),
                ('grvi', models.ImageField(blank=True, upload_to='processed_shots/GRVI')),
                ('gci', models.ImageField(blank=True, upload_to='processed_shots/GCI')),
                ('processed_on', models.DateTimeField(auto_now_add=True)),
                ('Picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.Picture')),
            ],
        ),
    ]
