# Generated by Django 3.0.1 on 2020-01-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0006_auto_20200105_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='processeddata',
            name='farm',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='farm.Farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='dwQK1G2A', max_length=120),
        ),
    ]
