# Generated by Django 3.0.1 on 2020-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_auto_20200105_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='QYdFd0Fl', max_length=120),
        ),
        migrations.DeleteModel(
            name='ProcessedData',
        ),
    ]
