# Generated by Django 3.0.1 on 2020-01-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0008_auto_20200105_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='X2eUDbL7', max_length=120),
        ),
    ]
