# Generated by Django 3.0.1 on 2020-01-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0009_auto_20200105_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(auto_created=True, default='9GD6dWqZ', max_length=120),
        ),
    ]
