# Generated by Django 3.0.1 on 2020-01-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0010_auto_20200106_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_lookup',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
