# Generated by Django 3.0.7 on 2020-06-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0012_auto_20200628_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_area',
            field=models.FloatField(),
        ),
    ]
